extends Node
## Autoload: the player's own presence in the world — Faith, and the Ember.
##
## The Ember is the game's signature mechanic and it lives here rather than on a
## scene node, because half the sim needs to ask where it is: villagers check it for
## a work-speed bonus, the blight checks it for suppression, monsters check it to
## decide whether to flinch. The visual node in the run scene follows THIS, not the
## other way round.

## Faith is designed as a flow, not a hoard. It accrues continuously from villagers
## who are fed, rested and lit, and is spent on powers both day and night — the day
## sinks exist specifically so hoarding until dusk is a real sacrifice.
const FAITH_MAX := 100.0
const FAITH_BASE_RATE := 0.6           ## per second with a baseline colony

var faith: float = 20.0

## The Ember's authoritative position in WORLD space. `ember_cell` is derived from
## it, so the light, the aura and the sim can never disagree about where it is.
var ember_pos: Vector2 = Vector2.ZERO
var ember_cell: int = -1
var ember_radius: int = 6
var ember_strength: int = 255

## Travel speed, in pixels per second, used to derive the glide duration. The Ember
## deliberately does NOT teleport: giving it travel time is what makes its position
## a real commitment. Rushing it to a breached wall at night has to cost something,
## or the "it can only be in one place" tension evaporates.
const TRAVEL_SPEED := 105.0
## Floor on the glide duration. Without it a one-tile hop resolves in ~0.15s, which
## reads as a snap — and short repositioning nudges are the most common Ember move
## there is, so they are exactly the ones that need to feel weighty.
const TRAVEL_MIN := 0.30
const TRAVEL_MAX := 2.4

## How fast the Ember chases the finger while it is being DRAGGED, as the rate of an
## exponential approach. A drag used to snap the Ember cell to cell, which both
## stuttered in 16px steps and parked the light up to half a tile away from the
## thumb. Chasing a free world-space target fixes the offset and keeps the weight:
## high enough that the Ember stays under the finger, low enough that it still reads
## as something you are hauling rather than something you are teleporting.
const DRAG_FOLLOW_RATE := 16.0
## Settle time when the finger lifts. The Ember ends on a cell centre so the light
## grid, the sim and the sprite cannot disagree about which tile it is on.
const DRAG_SETTLE_TIME := 0.12

var _light_handle: int = 0
var _travel: Tween = null
var _dragging: bool = false
var _drag_target: Vector2 = Vector2.ZERO

## Lights dropped by Emberfall, and when they expire. Kept here rather than as
## scene nodes so they survive a scene reload and are trivially saveable.
var _temp_lights: Array = []            ## [{handle, expires}]
## power id -> seconds until it can be cast again.
var _cooldowns: Dictionary = {}


func _ready() -> void:
	reset()


func reset() -> void:
	faith = 20.0
	ember_cell = -1
	ember_pos = Vector2.ZERO
	_light_handle = 0
	_temp_lights.clear()
	_cooldowns.clear()
	_dragging = false
	_kill_travel()


## Faith is generated by the colony, not by the clock. A well-fed, rested, well-lit
## village produces it steadily; a miserable one produces almost nothing. That is
## the loop the whole design hangs on — look after your people, and you get the
## power to protect them. Neglect them and you go into the night with an empty meter.
func step(delta: float) -> void:
	_expire_lights(delta)
	_tick_cooldowns(delta)
	if faith >= FAITH_MAX:
		return
	var rate := FAITH_BASE_RATE * faith_multiplier()
	if rate <= 0.0:
		return
	faith = minf(faith + rate * delta, FAITH_MAX)
	Events.faith_changed.emit(faith)


## How fast Faith accrues right now, as a multiple of the base rate. Exposed so the
## HUD can show the player WHY their Faith is crawling — a number that silently
## depends on morale is indistinguishable from a broken one.
func faith_multiplier() -> float:
	var pop := Colony.population()
	if pop <= 0:
		return 0.0

	# Mood maps to a multiplier around 1.0 at "content" (60). A colony in despair
	# still trickles a little rather than stopping dead, so a bad night is
	# recoverable instead of a death spiral.
	var mood_factor := clampf(Colony.average_mood() / 60.0, 0.15, 1.8)

	# More people means more worship, but with sharply diminishing returns so that
	# a large colony does not trivialise the Faith economy.
	var pop_factor := clampf(sqrt(float(pop) / 6.0), 0.4, 2.2)

	return mood_factor * pop_factor


## The light grid is restamped only when the Ember crosses into a new CELL, not on
## every sub-pixel of the glide. Restamping per frame would redo a whole disc of
## light sixty times a second for no visible gain.
func _process(delta: float) -> void:
	if ember_cell == -1:
		return
	# A drag steers a target rather than the Ember itself, so the follow stays smooth
	# however coarsely or unevenly the touch events happen to arrive.
	if _dragging:
		ember_pos = ember_pos.lerp(_drag_target, clampf(DRAG_FOLLOW_RATE * delta, 0.0, 1.0))
	var cell := World.grid.to_cell_index(ember_pos)
	if cell != -1 and cell != ember_cell:
		ember_cell = cell
		World.light_field.move_source(_light_handle, cell)
		Events.ember_moved.emit(ember_pos)


# --- The Ember ---------------------------------------------------------------------

## Snap the Ember somewhere with no travel at all. Run setup, saves, teleports —
## anything where there is no gesture to stay in step with.
func place_ember(cell: int) -> void:
	if not World.grid.is_valid_index(cell):
		return
	_dragging = false
	_kill_travel()
	ember_cell = cell
	ember_pos = World.grid.to_world_index(cell)
	if _light_handle == 0:
		_light_handle = World.light_field.add_source(cell, ember_radius, ember_strength)
	else:
		World.light_field.move_source(_light_handle, cell)
	Events.ember_moved.emit(ember_pos)


## Glide the Ember to a cell. Duration scales with distance so it holds a roughly
## constant speed, and eases out so it settles rather than stopping dead. Retargeting
## mid-flight simply replaces the tween — the Ember turns and continues.
func tween_ember_to(cell: int) -> void:
	if not World.grid.is_valid_index(cell) or ember_cell == -1:
		return
	var target := World.grid.to_world_index(cell)
	var duration := clampf(ember_pos.distance_to(target) / TRAVEL_SPEED, TRAVEL_MIN, TRAVEL_MAX)

	_dragging = false
	_kill_travel()
	_travel = create_tween()
	_travel.tween_property(self, "ember_pos", target, duration)\
		.set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_OUT)


# --- Dragging ---------------------------------------------------------------------
#
# Direct manipulation, so it does NOT go through the grid: the Ember follows a
# free world-space point and only settles onto a cell when the finger lifts.
# Rounding to the nearest tile mid-gesture is what made the light sit beside the
# thumb instead of under it.

## Take hold of the Ember. Any glide in flight is abandoned — the player's hand wins.
func begin_ember_drag() -> void:
	if ember_cell == -1:
		return
	_kill_travel()
	_dragging = true
	_drag_target = ember_pos


## Aim the drag. The Ember is not moved here; _process eases it toward this point.
func drag_ember_to(world_pos: Vector2) -> void:
	if not _dragging:
		return
	# Clamped to the map so a finger dragged past the edge cannot strand the Ember
	# where to_cell_index reads -1 and the light quietly stops moving with it.
	var rect := World.grid.world_rect()
	_drag_target = Vector2(
		clampf(world_pos.x, rect.position.x, rect.end.x - 1.0),
		clampf(world_pos.y, rect.position.y, rect.end.y - 1.0)
	)


## Let go. The Ember settles onto the centre of whichever tile it came to rest over.
func end_ember_drag() -> void:
	if not _dragging:
		return
	_dragging = false
	var cell := World.grid.to_cell_index(ember_pos)
	if cell == -1:
		return
	_kill_travel()
	_travel = create_tween()
	_travel.tween_property(self, "ember_pos", World.grid.to_world_index(cell), DRAG_SETTLE_TIME)\
		.set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_OUT)


func is_dragging() -> bool:
	return _dragging


func is_travelling() -> bool:
	return _travel != null and _travel.is_valid() and _travel.is_running()


func _kill_travel() -> void:
	if _travel != null and _travel.is_valid():
		_travel.kill()
	_travel = null


func ember_position() -> Vector2:
	return ember_pos


## True when a cell sits inside the Ember's aura. Hot path — called per agent per
## think, so it compares squared distances and never allocates.
func is_within_ember(cell: int) -> bool:
	if ember_cell == -1:
		return false
	return World.grid.dist_sq(cell, ember_cell) <= ember_radius * ember_radius


## Multiplier applied to villager work rate and mood retention inside the aura.
func work_bonus(cell: int) -> float:
	return 1.5 if is_within_ember(cell) else 1.0


# --- Faith -------------------------------------------------------------------------

# --- Powers ---------------------------------------------------------------------------

func cooldown_of(id: StringName) -> float:
	return _cooldowns.get(id, 0.0)


func can_cast(def: PowerDef) -> bool:
	return def != null and faith >= def.faith_cost and cooldown_of(def.id) <= 0.0


## Cast a power at a world position. Returns true if it actually went off — the
## caller should not assume success, because "not enough Faith" is a normal and
## frequent outcome rather than an error.
func cast(def: PowerDef, world_pos: Vector2) -> bool:
	if not can_cast(def):
		return false
	var centre := World.grid.to_cell_index(world_pos)
	if centre == -1:
		return false

	if not pay(def.faith_cost):
		return false
	_cooldowns[def.id] = def.cooldown

	match def.kind:
		PowerDef.Kind.LIGHT:
			_cast_light(def, centre)
		PowerDef.Kind.SMITE:
			_cast_smite(def, world_pos)
		PowerDef.Kind.PURIFY:
			_cast_purify(def, centre)

	Events.power_cast.emit(def.id, world_pos)
	return true


func _cast_light(def: PowerDef, centre: int) -> void:
	var handle := World.light_field.add_source(centre, def.radius, int(def.amount))
	if def.duration > 0.0:
		_temp_lights.append({"handle": handle, "expires": def.duration})
	# A new light changes how monsters want to route, so the field has to be redone.
	Threat.mark_field_dirty()


func _cast_smite(def: PowerDef, world_pos: Vector2) -> void:
	var reach := float(def.radius) * Grid.TILE_SIZE
	var reach_sq := reach * reach
	for m in Threat.monsters.duplicate():
		if not is_instance_valid(m) or not m.alive:
			continue
		if m.position.distance_squared_to(world_pos) <= reach_sq:
			m.take_damage(def.amount, null)


func _cast_purify(def: PowerDef, centre: int) -> void:
	var grid: Grid = World.grid
	var c := grid.coord(centre)
	for dy in range(-def.radius, def.radius + 1):
		for dx in range(-def.radius, def.radius + 1):
			if dx * dx + dy * dy > def.radius * def.radius:
				continue
			if not grid.is_valid(c.x + dx, c.y + dy):
				continue
			World.blight_field.purify(grid.index(c.x + dx, c.y + dy), int(def.amount))


func _expire_lights(delta: float) -> void:
	if _temp_lights.is_empty():
		return
	var kept: Array = []
	for entry: Dictionary in _temp_lights:
		entry["expires"] -= delta
		if entry["expires"] > 0.0:
			kept.append(entry)
		else:
			World.light_field.remove_source(entry["handle"])
			Threat.mark_field_dirty()
	_temp_lights = kept


func _tick_cooldowns(delta: float) -> void:
	for id in _cooldowns.keys():
		var remaining: float = _cooldowns[id] - delta
		if remaining <= 0.0:
			_cooldowns.erase(id)
		else:
			_cooldowns[id] = remaining


# --- Faith -------------------------------------------------------------------------

func can_pay(cost: float) -> bool:
	return faith >= cost


func pay(cost: float) -> bool:
	if not can_pay(cost):
		return false
	faith -= cost
	Events.faith_changed.emit(faith)
	return true
